export interface AutomationMCP {
  id: string
  slug: string
  name: string
  description: string
  longDescription: string
  githubUrl: string
  installCommand: string
  owner: string
  category: string
  categorySlug: string
  tags: string[]
  stars: number
  language: string
  license: string
  lastUpdated: string
  features: string[]
  riskLevel: 'safe' | 'caution' | 'grey-area'
  disclaimer: string
  country: 'india' | 'global'
}

export const AUTOMATION_MCPS: AutomationMCP[] = [
  // === INDIAN AUTOMATION (Grey Area) ===
  {
    id: 'auto-1',
    slug: 'irctc-tatkal-automation',
    name: 'IRCTC Tatkal Booking Automation',
    description: 'Automate IRCTC Tatkal ticket booking — auto-fill forms, handle captchas, and book tickets faster.',
    longDescription: 'Browser automation tool for IRCTC Tatkal ticket booking. Automates the entire booking flow including login, passenger details, captcha handling, and payment. Built with Cypress/Selenium for speed. Note: IRCTC ToS prohibits automated booking — use at your own risk.',
    githubUrl: 'https://github.com/shivamguys/irctc-cypress-automation',
    installCommand: 'git clone https://github.com/shivamguys/irctc-cypress-automation',
    owner: 'shivamguys',
    category: 'Travel & Booking',
    categorySlug: 'government',
    tags: ['IRCTC', 'Tatkal', 'Booking', 'Automation', 'Railways'],
    stars: 890,
    language: 'JavaScript',
    license: 'MIT',
    lastUpdated: '2025-03-15',
    features: [
      'Auto-fill passenger details',
      'Captcha solving with retries',
      'Auto-select preferred seats',
      'UPI/QR payment automation',
      'Food choice selection',
      'Auto-upgrade enabled',
    ],
    riskLevel: 'grey-area',
    disclaimer: 'IRCTC Terms of Service prohibit automated booking. This tool is for educational purposes. Using bots for ticket booking may result in account suspension.',
    country: 'india',
  },
  {
    id: 'auto-2',
    slug: 'irctc-tatkal-python',
    name: 'IRCTC Tatkal (Python)',
    description: 'Python-based IRCTC Tatkal automation with GUI — supports COD option and verified booking.',
    longDescription: 'Python automation script with a GUI interface for IRCTC Tatkal booking. Supports Cash on Delivery payment option, auto-fills all passenger details, and handles the booking flow. Includes a verified working version.',
    githubUrl: 'https://github.com/PrajinkyaPimpalghare/IRCTC-Automation-Tatkal-and-General-Ticket-Booking-',
    installCommand: 'git clone https://github.com/PrajinkyaPimpalghare/IRCTC-Automation-Tatkal-and-General-Ticket-Booking-',
    owner: 'PrajinkyaPimpalghare',
    category: 'Travel & Booking',
    categorySlug: 'government',
    tags: ['IRCTC', 'Tatkal', 'Python', 'GUI', 'COD'],
    stars: 650,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-01-20',
    features: [
      'GUI interface for easy use',
      'Cash on Delivery support',
      'Auto-fill all passenger details',
      'General & Tatkal booking',
      'Multiple passenger support',
      'Verified working version',
    ],
    riskLevel: 'grey-area',
    disclaimer: 'IRCTC Terms of Service prohibit automated booking. This tool is for educational purposes only. Account suspension risk exists.',
    country: 'india',
  },
  {
    id: 'auto-3',
    slug: 'flipkart-scraper',
    name: 'Flipkart Price Scraper',
    description: 'Scrape product prices, reviews, and details from Flipkart — track prices and get deal alerts.',
    longDescription: 'API and scraper for Flipkart product data. Search products, get prices, read reviews, track price history, and set up deal alerts. Useful for price comparison and deal hunting on India\'s largest e-commerce platform.',
    githubUrl: 'https://github.com/dvishal485/flipkart-scraper-api',
    installCommand: 'git clone https://github.com/dvishal485/flipkart-scraper-api',
    owner: 'dvishal485',
    category: 'E-commerce',
    categorySlug: 'e-commerce',
    tags: ['Flipkart', 'Scraping', 'Prices', 'E-commerce', 'India'],
    stars: 420,
    language: 'Rust',
    license: 'MIT',
    lastUpdated: '2025-02-10',
    features: [
      'Search products by keyword',
      'Get product prices & details',
      'Read customer reviews',
      'Track price history',
      'Deal alert notifications',
      'Category browsing',
    ],
    riskLevel: 'caution',
    disclaimer: 'Web scraping may violate Flipkart Terms of Service. Data accuracy is not guaranteed. Use for personal price tracking only.',
    country: 'india',
  },
  {
    id: 'auto-4',
    slug: 'zerodha-algo-trading',
    name: 'Zerodha Algo Trading Bot',
    description: 'Automated trading on Zerodha using AI/ML — live bots, indicators, screeners, and backtesting.',
    longDescription: 'Full algorithmic trading system for Zerodha Kite. Uses AI/ML models for trade signals, includes live trading bots, technical indicators, stock screeners, and backtesting framework. Connects via official Kite Connect API.',
    githubUrl: 'https://github.com/yugeshk/Zerodha_Live_Automate_Trading-_using_AI_ML_on_Indian_stock_market',
    installCommand: 'git clone https://github.com/yugeshk/Zerodha_Live_Automate_Trading-_using_AI_ML_on_Indian_stock_market',
    owner: 'yugeshk',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Zerodha', 'Algo Trading', 'AI/ML', 'Bots', 'NSE'],
    stars: 380,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-04-05',
    features: [
      'Live automated trading',
      'AI/ML-based trade signals',
      'Technical indicators library',
      'Stock screener',
      'Backtesting framework',
      'WebSocket real-time data',
    ],
    riskLevel: 'caution',
    disclaimer: 'Algorithmic trading carries significant financial risk. Past performance does not guarantee future results. SEBI regulations apply to algo trading in India. Use official Kite Connect API with proper authorization.',
    country: 'india',
  },

  // === GLOBAL PLATFORM AUTOMATION ===
  {
    id: 'auto-5',
    slug: 'instagram-mcp-server',
    name: 'Instagram MCP Server',
    description: 'Full Instagram automation — posts, comments, DMs, stories, hashtags, reels, carousels, and analytics.',
    longDescription: 'Comprehensive Instagram MCP server with 23 tools for the Graph API. Manage posts, reply to comments, send DMs, publish stories and reels, create carousels, track hashtags, and access analytics. Uses official Instagram Graph API.',
    githubUrl: 'https://github.com/mcpware/instagram-mcp',
    installCommand: 'npx @mcpware/instagram-mcp',
    owner: 'mcpware',
    category: 'Social Media',
    categorySlug: 'communication',
    tags: ['Instagram', 'Social Media', 'Posts', 'DMs', 'Analytics'],
    stars: 340,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-10',
    features: [
      'Publish posts and carousels',
      'Manage comments and replies',
      'Send and read DMs',
      'Publish stories and reels',
      'Track hashtag performance',
      'Access account analytics',
      'Schedule content',
      'Manage followers',
    ],
    riskLevel: 'caution',
    disclaimer: 'Uses Instagram Graph API (official). Requires a Facebook Business account. Aggressive automation may trigger rate limits or account restrictions. Follow Instagram Platform Policy.',
    country: 'global',
  },
  {
    id: 'auto-6',
    slug: 'twitter-x-mcp',
    name: 'Twitter/X MCP Server',
    description: 'Post tweets, manage threads, search, and interact with Twitter/X through AI.',
    longDescription: 'MCP server for Twitter/X platform. Post tweets, create threads, search tweets, manage likes and retweets, access analytics, and automate Twitter workflows. Supports both v1.1 and v2 APIs.',
    githubUrl: 'https://github.com/taazkareem/twitter-mcp-server',
    installCommand: 'npx twitter-mcp-server',
    owner: 'taazkareem',
    category: 'Social Media',
    categorySlug: 'communication',
    tags: ['Twitter', 'X', 'Tweets', 'Social Media', 'Threads'],
    stars: 520,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-18',
    features: [
      'Post tweets and threads',
      'Search tweets and users',
      'Like, retweet, and reply',
      'Manage followers/following',
      'Access tweet analytics',
      'Schedule tweets',
      'Delete tweets',
      'Manage lists',
    ],
    riskLevel: 'caution',
    disclaimer: 'Twitter/X API access requires a developer account. Free tier has strict rate limits. Automated posting may violate Twitter Rules if used for spam. Follow Twitter Developer Policy.',
    country: 'global',
  },
  {
    id: 'auto-7',
    slug: 'youtube-mcp',
    name: 'YouTube MCP Server',
    description: 'Fetch YouTube subtitles, video metadata, channel info, and search videos with AI.',
    longDescription: 'MCP server for YouTube data access. Fetch video subtitles/transcripts, get video metadata, search videos, access channel information, and analyze content. Primarily read-only — does not upload or modify content.',
    githubUrl: 'https://github.com/anaisbetts/mcp-youtube',
    installCommand: 'npx mcp-youtube',
    owner: 'anaisbetts',
    category: 'Media & Content',
    categorySlug: 'communication',
    tags: ['YouTube', 'Videos', 'Subtitles', 'Transcripts', 'Search'],
    stars: 680,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-28',
    features: [
      'Fetch video subtitles/transcripts',
      'Get video metadata (title, views, likes)',
      'Search videos by keyword',
      'Access channel information',
      'Get video comments',
      'Playlist management',
    ],
    riskLevel: 'safe',
    disclaimer: 'Uses YouTube Data API (official). Requires a Google API key. Read-only access — does not upload or modify content. Respect YouTube ToS and API quotas.',
    country: 'global',
  },
  {
    id: 'auto-8',
    slug: 'linkedin-mcp',
    name: 'LinkedIn MCP Server',
    description: 'Interact with LinkedIn feeds, jobs, and profiles — post content and search opportunities.',
    longDescription: 'MCP server for LinkedIn platform. Access your feed, search jobs, post content, manage connections, and interact with LinkedIn\'s professional network through your AI assistant.',
    githubUrl: 'https://github.com/adhikasp/mcp-linkedin',
    installCommand: 'npx mcp-linkedin',
    owner: 'adhikasp',
    category: 'Social Media',
    categorySlug: 'communication',
    tags: ['LinkedIn', 'Jobs', 'Professional', 'Networking', 'Posts'],
    stars: 290,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-04-15',
    features: [
      'Read and post to feed',
      'Search job listings',
      'View profile information',
      'Manage connections',
      'Send messages',
      'Access company pages',
    ],
    riskLevel: 'caution',
    disclaimer: 'LinkedIn aggressively restricts automation. Unofficial API usage may result in account restriction or ban. Use sparingly and respect rate limits.',
    country: 'global',
  },
  {
    id: 'auto-9',
    slug: 'google-drive-mcp',
    name: 'Google Drive MCP',
    description: 'Manage Google Drive files, Docs, Sheets, Slides, and Calendar through AI.',
    longDescription: 'MCP server for Google Workspace. Manage files in Google Drive, create and edit Docs, work with Sheets data, manage Slides presentations, and access Calendar events. Uses official Google APIs with OAuth.',
    githubUrl: 'https://github.com/piotr-agier/google-drive-mcp',
    installCommand: 'npx google-drive-mcp',
    owner: 'piotr-agier',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Google Drive', 'Docs', 'Sheets', 'Calendar', 'Google'],
    stars: 450,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-12',
    features: [
      'Upload and download files',
      'Create and edit Google Docs',
      'Read and write Sheets data',
      'Manage Slides presentations',
      'Access Calendar events',
      'Share and permission management',
      'Search across Drive',
      'Folder organization',
    ],
    riskLevel: 'safe',
    disclaimer: 'Uses official Google APIs with OAuth authentication. Requires Google Cloud project setup. Respects Google API quotas and rate limits.',
    country: 'global',
  },
  {
    id: 'auto-10',
    slug: 'telegram-mcp',
    name: 'Telegram MCP Server',
    description: 'Send messages, manage groups, create bots, and automate Telegram workflows.',
    longDescription: 'MCP server for Telegram messaging platform. Send and receive messages, manage groups and channels, create and control bots, handle media, and automate Telegram workflows. Uses official Telegram Bot API.',
    githubUrl: 'https://github.com/nichochar/telegram-mcp',
    installCommand: 'npx telegram-mcp',
    owner: 'nichochar',
    category: 'Communication',
    categorySlug: 'communication',
    tags: ['Telegram', 'Messaging', 'Bots', 'Groups', 'Channels'],
    stars: 380,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-20',
    features: [
      'Send and receive messages',
      'Manage groups and channels',
      'Create and control bots',
      'Handle media (photos, videos, docs)',
      'Inline keyboards and buttons',
      'Webhook management',
      'User and chat info',
      'Scheduled messages',
    ],
    riskLevel: 'safe',
    disclaimer: 'Uses official Telegram Bot API. Requires a bot token from @BotFather. Fully supported and encouraged by Telegram.',
    country: 'global',
  },
  {
    id: 'auto-11',
    slug: 'instagram-dm-automation',
    name: 'Instagram DM Automation',
    description: 'Send Instagram DMs programmatically — bulk messaging, auto-replies, and outreach automation.',
    longDescription: 'Tool for automating Instagram Direct Messages. Send bulk DMs, set up auto-replies, manage outreach campaigns, and handle customer inquiries. Uses unofficial methods — higher risk of account restriction.',
    githubUrl: 'https://github.com/trypeggy/instagram_dm_mcp',
    installCommand: 'npx instagram-dm-mcp',
    owner: 'trypeggy',
    category: 'Social Media',
    categorySlug: 'communication',
    tags: ['Instagram', 'DMs', 'Outreach', 'Bulk Messaging', 'Automation'],
    stars: 180,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-03-28',
    features: [
      'Send bulk DMs',
      'Auto-reply to messages',
      'Outreach campaign management',
      'Template-based messaging',
      'Rate limiting built-in',
      'Contact list management',
    ],
    riskLevel: 'grey-area',
    disclaimer: 'Instagram strictly prohibits automated DMs and bulk messaging. Using this tool WILL likely result in account restriction, shadow ban, or permanent ban. For educational purposes only.',
    country: 'global',
  },
  {
    id: 'auto-12',
    slug: 'social-media-agent',
    name: 'Social Media Agent (LangChain)',
    description: 'AI agent for sourcing, curating, and scheduling social media posts across platforms.',
    longDescription: 'LangChain-powered social media agent that sources content, curates posts, and schedules them across multiple platforms. Includes human-in-the-loop approval before posting. Built by the LangChain team.',
    githubUrl: 'https://github.com/langchain-ai/social-media-agent',
    installCommand: 'git clone https://github.com/langchain-ai/social-media-agent',
    owner: 'langchain-ai',
    category: 'Social Media',
    categorySlug: 'communication',
    tags: ['Social Media', 'AI Agent', 'Scheduling', 'Content', 'LangChain'],
    stars: 1200,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-05-01',
    features: [
      'Multi-platform posting',
      'Content sourcing and curation',
      'AI-generated captions',
      'Scheduling and queue',
      'Human-in-the-loop approval',
      'Analytics tracking',
      'Hashtag suggestions',
      'Optimal timing recommendations',
    ],
    riskLevel: 'safe',
    disclaimer: 'Uses official APIs where available. Human-in-the-loop ensures content is reviewed before posting. Follow each platform\'s content and automation policies.',
    country: 'global',
  },
]
