export interface FeaturedMCP {
  id: string
  slug: string
  name: string
  description: string
  longDescription: string
  githubUrl: string
  installCommand: string
  owner: string
  category: string
  categorySlug: string
  tags: string[]
  stars: number
  language: string
  license: string
  lastUpdated: string
  features: string[]
  compatibility: string[]
  setupSteps: string[]
}

export const FEATURED_MCPS: FeaturedMCP[] = [
  {
    id: 'featured-1',
    slug: 'github-official',
    name: 'GitHub MCP (Official)',
    description: 'GitHub\'s official MCP server — manage repos, issues, PRs, code search, and Actions directly from your AI assistant.',
    longDescription: 'The official GitHub MCP server maintained by GitHub. Provides comprehensive access to GitHub APIs including repository management, issue tracking, pull request workflows, code search, Actions management, and more. The most widely deployed MCP server in the ecosystem.',
    githubUrl: 'https://github.com/github/github-mcp-server',
    installCommand: 'npx @github/mcp-server',
    owner: 'github',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['GitHub', 'Git', 'Code', 'PRs', 'Issues', 'CI/CD'],
    stars: 12500,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-28',
    features: [
      'Create, clone, and manage repositories',
      'Create and review pull requests',
      'Manage issues and labels',
      'Search code across repositories',
      'Trigger and monitor GitHub Actions',
      'Manage branches and releases',
      'Access commit history and diffs',
      'Manage GitHub Projects boards',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf', 'Kiro'],
    setupSteps: [
      'Generate a GitHub Personal Access Token at github.com/settings/tokens',
      'Install: npx @github/mcp-server',
      'Set GITHUB_TOKEN environment variable',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-2',
    slug: 'playwright-official',
    name: 'Playwright MCP (Microsoft)',
    description: 'Microsoft\'s official Playwright MCP — automate browsers, scrape web pages, fill forms, and test websites with AI.',
    longDescription: 'The official Playwright MCP server from Microsoft. Enables AI assistants to control browsers programmatically — navigate pages, click elements, fill forms, take screenshots, and run end-to-end tests. One of the most starred MCP servers on GitHub (~12K stars).',
    githubUrl: 'https://github.com/microsoft/playwright-mcp',
    installCommand: 'npx @playwright/mcp',
    owner: 'microsoft',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Browser', 'Automation', 'Testing', 'Scraping', 'E2E'],
    stars: 12000,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-25',
    features: [
      'Navigate to any URL',
      'Click, type, and interact with elements',
      'Take screenshots and PDFs',
      'Fill forms automatically',
      'Run accessibility audits',
      'Execute JavaScript in page context',
      'Handle authentication flows',
      'Multi-browser support (Chrome, Firefox, Safari)',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Install: npx @playwright/mcp',
      'No API key needed — runs locally',
      'Browsers are auto-downloaded on first run',
      'Add to your AI client MCP config',
    ],
  },
  {
    id: 'featured-3',
    slug: 'context7',
    name: 'Context7',
    description: 'Up-to-date documentation for any library — the most popular MCP server by views. Eliminates hallucinated API calls.',
    longDescription: 'Context7 provides real-time, accurate documentation for thousands of libraries and frameworks. When your AI assistant needs to use a library, Context7 fetches the latest docs so it doesn\'t hallucinate outdated APIs. Dominates MCP directories by a 2x margin in views.',
    githubUrl: 'https://github.com/upstash/context7-mcp',
    installCommand: 'npx context7-mcp',
    owner: 'upstash',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Documentation', 'Libraries', 'API Reference', 'Anti-hallucination'],
    stars: 8500,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-20',
    features: [
      'Fetch latest docs for any npm/pip package',
      'Prevents AI from hallucinating outdated APIs',
      'Covers 10,000+ libraries',
      'Auto-updates when libraries release new versions',
      'Structured output for AI consumption',
      'Works offline with cached docs',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf', 'Kiro'],
    setupSteps: [
      'Install: npx context7-mcp',
      'No API key required',
      'Add to your AI client MCP config',
      'Start asking about any library',
    ],
  },
  {
    id: 'featured-4',
    slug: 'stripe-official',
    name: 'Stripe MCP (Official)',
    description: 'Stripe\'s official MCP server — process payments, manage subscriptions, handle refunds, and access financial data.',
    longDescription: 'The official Stripe MCP server from Stripe\'s Agent Toolkit. Enables AI assistants to interact with Stripe\'s payment infrastructure — create payment intents, manage subscriptions, process refunds, generate invoices, and access transaction data.',
    githubUrl: 'https://github.com/stripe/agent-toolkit',
    installCommand: 'npx @stripe/mcp-server',
    owner: 'stripe',
    category: 'Payments',
    categorySlug: 'payments',
    tags: ['Payments', 'Subscriptions', 'Invoices', 'Refunds', 'Global'],
    stars: 4200,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-22',
    features: [
      'Create payment intents & charges',
      'Manage subscriptions & plans',
      'Process refunds',
      'Generate invoices',
      'List transactions & balance',
      'Manage customers',
      'Handle webhooks',
      'Access Stripe Dashboard data',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get your Stripe API key from dashboard.stripe.com',
      'Install: npx @stripe/mcp-server',
      'Set STRIPE_SECRET_KEY environment variable',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-5',
    slug: 'notion-official',
    name: 'Notion MCP (Official)',
    description: 'Notion\'s official MCP server — create pages, query databases, manage workspaces, and organize knowledge.',
    longDescription: 'The official Notion MCP server. Enables AI assistants to interact with your Notion workspace — create and edit pages, query databases, manage properties, search content, and build automated workflows for knowledge management.',
    githubUrl: 'https://github.com/makenotion/notion-mcp-server',
    installCommand: 'npx @notionhq/mcp-server',
    owner: 'makenotion',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Notion', 'Notes', 'Databases', 'Wiki', 'Productivity'],
    stars: 3800,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-18',
    features: [
      'Create and edit pages',
      'Query and filter databases',
      'Search across workspace',
      'Manage page properties',
      'Create database entries',
      'Organize with tags and relations',
      'Access page content as markdown',
      'Manage workspace members',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Create a Notion integration at notion.so/my-integrations',
      'Share relevant pages/databases with the integration',
      'Install: npx @notionhq/mcp-server',
      'Set NOTION_API_KEY environment variable',
    ],
  },
  {
    id: 'featured-6',
    slug: 'supabase-mcp',
    name: 'Supabase MCP',
    description: 'Connect to Supabase — manage databases, auth, edge functions, storage, and real-time subscriptions.',
    longDescription: 'Community MCP server for Supabase, the open-source Firebase alternative. Manage your PostgreSQL database, authentication, edge functions, file storage, and real-time subscriptions through your AI assistant.',
    githubUrl: 'https://github.com/supabase-community/supabase-mcp',
    installCommand: 'npx supabase-mcp',
    owner: 'supabase-community',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['Supabase', 'PostgreSQL', 'Auth', 'Database', 'Realtime'],
    stars: 3200,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-15',
    features: [
      'Run SQL queries on your database',
      'Manage tables and schemas',
      'Handle user authentication',
      'Upload and manage files',
      'Deploy edge functions',
      'Set up real-time subscriptions',
      'Manage RLS policies',
      'Access project settings',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get your Supabase project URL and anon key',
      'Install: npx supabase-mcp',
      'Set SUPABASE_URL and SUPABASE_KEY',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-7',
    slug: 'slack-mcp',
    name: 'Slack MCP',
    description: 'Send messages, manage channels, search conversations, and automate Slack workflows with AI.',
    longDescription: 'MCP server for Slack integration. Send and read messages, create channels, manage users, search conversation history, and build automated communication workflows. Essential for teams using Slack as their primary communication tool.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-slack',
    owner: 'modelcontextprotocol',
    category: 'Communication',
    categorySlug: 'communication',
    tags: ['Slack', 'Messaging', 'Teams', 'Channels', 'Automation'],
    stars: 2800,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-10',
    features: [
      'Send messages to channels and DMs',
      'Read conversation history',
      'Search messages across workspace',
      'Create and manage channels',
      'Upload files and snippets',
      'Set reminders and notifications',
      'Manage user groups',
      'Access workspace analytics',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Create a Slack app at api.slack.com/apps',
      'Install the app to your workspace',
      'Get the Bot User OAuth Token',
      'Set SLACK_BOT_TOKEN environment variable',
    ],
  },
  {
    id: 'featured-8',
    slug: 'cloudflare-mcp',
    name: 'Cloudflare MCP (Official)',
    description: 'Deploy Workers, manage KV/R2/D1, configure DNS, and control your Cloudflare infrastructure with AI.',
    longDescription: 'The official Cloudflare MCP server. Deploy and manage Workers, interact with KV stores, R2 buckets, D1 databases, configure DNS records, and manage your entire Cloudflare infrastructure through natural language.',
    githubUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    installCommand: 'npx @cloudflare/mcp-server',
    owner: 'cloudflare',
    category: 'Cloud & Infrastructure',
    categorySlug: 'cloud-infra',
    tags: ['Cloudflare', 'Workers', 'CDN', 'DNS', 'Edge'],
    stars: 3500,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-20',
    features: [
      'Deploy and manage Workers',
      'CRUD operations on KV stores',
      'Manage R2 object storage',
      'Query D1 databases',
      'Configure DNS records',
      'Manage firewall rules',
      'View analytics and logs',
      'Manage Pages deployments',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get your Cloudflare API token from dash.cloudflare.com',
      'Install: npx @cloudflare/mcp-server',
      'Set CLOUDFLARE_API_TOKEN environment variable',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-9',
    slug: 'firecrawl-mcp',
    name: 'Firecrawl MCP',
    description: 'Crawl and scrape any website into clean markdown — perfect for feeding web content to AI agents.',
    longDescription: 'Firecrawl MCP server for web scraping and crawling. Convert any website into clean, structured markdown that AI can understand. Handles JavaScript rendering, pagination, and anti-bot measures. Essential for AI agents that need web data.',
    githubUrl: 'https://github.com/mendableai/firecrawl-mcp-server',
    installCommand: 'npx firecrawl-mcp',
    owner: 'mendableai',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['Scraping', 'Crawling', 'Markdown', 'Web Data', 'AI'],
    stars: 2900,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-12',
    features: [
      'Crawl entire websites',
      'Convert pages to clean markdown',
      'Handle JavaScript-rendered content',
      'Extract structured data',
      'Respect robots.txt',
      'Rate limiting built-in',
      'Screenshot capture',
      'PDF extraction',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Get a Firecrawl API key at firecrawl.dev',
      'Install: npx firecrawl-mcp',
      'Set FIRECRAWL_API_KEY environment variable',
      'Start crawling websites',
    ],
  },
  {
    id: 'featured-10',
    slug: 'brave-search-mcp',
    name: 'Brave Search MCP',
    description: 'Web search powered by Brave — give your AI assistant access to real-time internet search results.',
    longDescription: 'MCP server for Brave Search API. Enables AI assistants to search the web in real-time, getting current information that\'s not in their training data. Returns structured results with snippets, URLs, and metadata.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-brave-search',
    owner: 'modelcontextprotocol',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['Search', 'Web', 'Real-time', 'Internet', 'Research'],
    stars: 2500,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-08',
    features: [
      'Web search with real-time results',
      'News search',
      'Image search',
      'Local search (businesses, places)',
      'Structured snippets',
      'Safe search filtering',
      'Multiple result types',
      'No tracking or ads',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf', 'Kiro'],
    setupSteps: [
      'Get a free Brave Search API key at brave.com/search/api',
      'Install: npx @modelcontextprotocol/server-brave-search',
      'Set BRAVE_API_KEY environment variable',
      'Your AI can now search the web',
    ],
  },
  {
    id: 'featured-11',
    slug: 'filesystem-mcp',
    name: 'Filesystem MCP',
    description: 'Read, write, and manage local files and directories — the essential MCP for file-based AI workflows.',
    longDescription: 'The official filesystem MCP server from the Model Context Protocol team. Gives AI assistants safe, controlled access to your local filesystem — read files, write content, create directories, and search for files. Includes configurable access controls.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-filesystem',
    owner: 'modelcontextprotocol',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Filesystem', 'Files', 'Local', 'Read', 'Write'],
    stars: 2200,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-10',
    features: [
      'Read file contents',
      'Write and create files',
      'Create directories',
      'List directory contents',
      'Move and rename files',
      'Search files by pattern',
      'Configurable access boundaries',
      'File metadata access',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf', 'Kiro'],
    setupSteps: [
      'Install: npx @modelcontextprotocol/server-filesystem',
      'Configure allowed directories in MCP config',
      'No API key needed — runs locally',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-12',
    slug: 'postgres-mcp',
    name: 'PostgreSQL MCP',
    description: 'Query and manage PostgreSQL databases — run SQL, inspect schemas, and analyze data with AI.',
    longDescription: 'MCP server for PostgreSQL database interaction. Run SQL queries, inspect table schemas, manage indexes, and perform data analysis through your AI assistant. Supports read-only mode for safe production access.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-postgres',
    owner: 'modelcontextprotocol',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['PostgreSQL', 'SQL', 'Database', 'Queries', 'Schema'],
    stars: 2100,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-05',
    features: [
      'Run SQL queries',
      'Inspect table schemas',
      'List databases and tables',
      'View indexes and constraints',
      'Read-only mode for safety',
      'Connection pooling',
      'Query result formatting',
      'Schema migration support',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Have a PostgreSQL database running',
      'Install: npx @modelcontextprotocol/server-postgres',
      'Set DATABASE_URL connection string',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-13',
    slug: 'linear-mcp',
    name: 'Linear MCP',
    description: 'Manage Linear issues, projects, and cycles — streamline your project management with AI.',
    longDescription: 'MCP server for Linear, the modern project management tool. Create and update issues, manage projects and cycles, track team velocity, and automate workflow transitions through your AI assistant.',
    githubUrl: 'https://github.com/jerhadf/linear-mcp-server',
    installCommand: 'npx linear-mcp-server',
    owner: 'jerhadf',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Linear', 'Issues', 'Project Management', 'Agile', 'Tracking'],
    stars: 1800,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-01',
    features: [
      'Create and update issues',
      'Manage projects and milestones',
      'Track cycles and sprints',
      'Assign and label issues',
      'Search across workspace',
      'View team workload',
      'Automate status transitions',
      'Access analytics and metrics',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get a Linear API key from linear.app/settings/api',
      'Install: npx linear-mcp-server',
      'Set LINEAR_API_KEY environment variable',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-14',
    slug: 'sentry-mcp',
    name: 'Sentry MCP',
    description: 'Monitor errors, track performance, and debug issues in production with Sentry\'s MCP server.',
    longDescription: 'MCP server for Sentry error monitoring. Query error events, analyze stack traces, track performance metrics, and manage issue assignments through your AI assistant. Debug production issues faster with AI-powered analysis.',
    githubUrl: 'https://github.com/getsentry/sentry-mcp',
    installCommand: 'npx @sentry/mcp-server',
    owner: 'getsentry',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Sentry', 'Errors', 'Monitoring', 'Debugging', 'Performance'],
    stars: 1600,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-18',
    features: [
      'Query error events and issues',
      'Analyze stack traces',
      'Track performance metrics',
      'Manage issue assignments',
      'View release health',
      'Search by error message',
      'Access breadcrumbs and context',
      'Monitor transaction performance',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get your Sentry auth token from sentry.io/settings/auth-tokens',
      'Install: npx @sentry/mcp-server',
      'Set SENTRY_AUTH_TOKEN environment variable',
      'Configure your organization slug',
    ],
  },
  {
    id: 'featured-15',
    slug: 'docker-mcp',
    name: 'Docker MCP',
    description: 'Manage Docker containers, images, volumes, and networks — run and orchestrate containers with AI.',
    longDescription: 'MCP server for Docker container management. Build images, run containers, manage volumes and networks, view logs, and orchestrate multi-container applications through your AI assistant. Essential for DevOps workflows.',
    githubUrl: 'https://github.com/docker/docker-mcp',
    installCommand: 'npx @docker/mcp-server',
    owner: 'docker',
    category: 'Cloud & Infrastructure',
    categorySlug: 'cloud-infra',
    tags: ['Docker', 'Containers', 'DevOps', 'Images', 'Orchestration'],
    stars: 1500,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-14',
    features: [
      'Build Docker images',
      'Run and manage containers',
      'View container logs',
      'Manage volumes and networks',
      'Docker Compose support',
      'Image registry operations',
      'Container health monitoring',
      'Resource usage stats',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Ensure Docker Desktop is running',
      'Install: npx @docker/mcp-server',
      'No API key needed — uses local Docker socket',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-16',
    slug: 'memory-mcp',
    name: 'Memory MCP',
    description: 'Give your AI persistent memory — store and retrieve knowledge across conversations.',
    longDescription: 'MCP server that provides persistent memory for AI assistants. Store facts, preferences, and context that persists across conversations. Uses a knowledge graph approach to organize and retrieve information intelligently.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-memory',
    owner: 'modelcontextprotocol',
    category: 'AI & ML',
    categorySlug: 'ai-ml',
    tags: ['Memory', 'Knowledge Graph', 'Persistence', 'Context', 'AI'],
    stars: 2200,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-10',
    features: [
      'Store facts and knowledge',
      'Retrieve relevant memories',
      'Knowledge graph structure',
      'Entity and relation management',
      'Semantic search over memories',
      'Conversation context persistence',
      'Memory consolidation',
      'Export and backup',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Install: npx @modelcontextprotocol/server-memory',
      'No API key needed — stores locally',
      'Configure storage path in MCP config',
      'Your AI now remembers across sessions',
    ],
  },
  {
    id: 'featured-17',
    slug: 'google-maps-mcp',
    name: 'Google Maps MCP',
    description: 'Geocoding, directions, places search, and distance calculations with Google Maps APIs.',
    longDescription: 'MCP server for Google Maps Platform. Get directions, search for places, calculate distances, geocode addresses, and access Street View imagery through your AI assistant. Essential for location-based applications.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-google-maps',
    owner: 'modelcontextprotocol',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['Maps', 'Geocoding', 'Directions', 'Places', 'Location'],
    stars: 1900,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-06',
    features: [
      'Geocode addresses to coordinates',
      'Get driving/walking/transit directions',
      'Search for nearby places',
      'Calculate distance matrices',
      'Place details and reviews',
      'Reverse geocoding',
      'Elevation data',
      'Time zone lookups',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get a Google Maps API key from console.cloud.google.com',
      'Enable Maps, Places, and Directions APIs',
      'Install: npx @modelcontextprotocol/server-google-maps',
      'Set GOOGLE_MAPS_API_KEY environment variable',
    ],
  },
  {
    id: 'featured-18',
    slug: 'puppeteer-mcp',
    name: 'Puppeteer MCP',
    description: 'Browser automation with Puppeteer — navigate, screenshot, scrape, and interact with web pages.',
    longDescription: 'MCP server using Puppeteer for browser automation. Control Chrome/Chromium programmatically — navigate pages, take screenshots, generate PDFs, scrape content, and automate web interactions. Lighter alternative to Playwright MCP.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-puppeteer',
    owner: 'modelcontextprotocol',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Puppeteer', 'Browser', 'Chrome', 'Scraping', 'Automation'],
    stars: 1700,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-08',
    features: [
      'Navigate to URLs',
      'Take full-page screenshots',
      'Generate PDFs',
      'Click and type interactions',
      'Evaluate JavaScript',
      'Handle cookies and sessions',
      'Network request interception',
      'Mobile device emulation',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Install: npx @modelcontextprotocol/server-puppeteer',
      'Chrome is auto-downloaded on first run',
      'No API key needed — runs locally',
      'Add to your AI client MCP config',
    ],
  },
  {
    id: 'featured-19',
    slug: 'vercel-mcp',
    name: 'Vercel MCP',
    description: 'Deploy to Vercel, manage projects, check deployments, and configure domains with AI.',
    longDescription: 'MCP server for Vercel platform management. Deploy projects, check deployment status, manage environment variables, configure custom domains, and access deployment logs through your AI assistant.',
    githubUrl: 'https://github.com/vercel/vercel-mcp',
    installCommand: 'npx @vercel/mcp-server',
    owner: 'vercel',
    category: 'Cloud & Infrastructure',
    categorySlug: 'cloud-infra',
    tags: ['Vercel', 'Deployment', 'Hosting', 'Serverless', 'Next.js'],
    stars: 1400,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-16',
    features: [
      'Trigger deployments',
      'Check deployment status',
      'Manage environment variables',
      'Configure custom domains',
      'View deployment logs',
      'Manage project settings',
      'Access analytics data',
      'Rollback deployments',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get a Vercel token from vercel.com/account/tokens',
      'Install: npx @vercel/mcp-server',
      'Set VERCEL_TOKEN environment variable',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-20',
    slug: 'figma-mcp',
    name: 'Figma MCP',
    description: 'Access Figma designs — read frames, extract styles, get component data, and bridge design-to-code.',
    longDescription: 'MCP server for Figma design platform. Access your Figma files, read frame structures, extract design tokens (colors, typography, spacing), get component properties, and bridge the gap between design and development.',
    githubUrl: 'https://github.com/nichochar/figma-mcp',
    installCommand: 'npx figma-mcp',
    owner: 'nichochar',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Figma', 'Design', 'UI', 'Components', 'Design Tokens'],
    stars: 1300,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-10',
    features: [
      'Read Figma file structure',
      'Extract design tokens',
      'Get component properties',
      'Access frame dimensions',
      'Export assets',
      'Read text content',
      'Get color and typography styles',
      'Navigate page hierarchy',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get a Figma Personal Access Token from figma.com/developers',
      'Install: npx figma-mcp',
      'Set FIGMA_ACCESS_TOKEN environment variable',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-21',
    slug: 'todoist-mcp',
    name: 'Todoist MCP',
    description: 'Manage tasks, projects, and labels in Todoist — your AI-powered task management assistant.',
    longDescription: 'MCP server for Todoist task management. Create and complete tasks, manage projects, set due dates and priorities, organize with labels, and build productivity workflows through your AI assistant.',
    githubUrl: 'https://github.com/abhiz123/todoist-mcp-server',
    installCommand: 'npx todoist-mcp-server',
    owner: 'abhiz123',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Todoist', 'Tasks', 'Productivity', 'GTD', 'Planning'],
    stars: 950,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-28',
    features: [
      'Create and complete tasks',
      'Manage projects and sections',
      'Set due dates and priorities',
      'Organize with labels',
      'Add comments to tasks',
      'Search and filter tasks',
      'Recurring task support',
      'Productivity stats',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get your Todoist API token from todoist.com/app/settings/integrations/developer',
      'Install: npx todoist-mcp-server',
      'Set TODOIST_API_TOKEN environment variable',
      'Start managing tasks with AI',
    ],
  },
  {
    id: 'featured-22',
    slug: 'aws-mcp',
    name: 'AWS MCP',
    description: 'Interact with AWS services — S3, Lambda, DynamoDB, EC2, and more through your AI assistant.',
    longDescription: 'MCP server for Amazon Web Services. Manage S3 buckets, invoke Lambda functions, query DynamoDB tables, control EC2 instances, and interact with 200+ AWS services through natural language commands.',
    githubUrl: 'https://github.com/aws/aws-mcp',
    installCommand: 'npx @aws/mcp-server',
    owner: 'aws',
    category: 'Cloud & Infrastructure',
    categorySlug: 'cloud-infra',
    tags: ['AWS', 'S3', 'Lambda', 'DynamoDB', 'Cloud'],
    stars: 2400,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-22',
    features: [
      'Manage S3 buckets and objects',
      'Invoke Lambda functions',
      'Query DynamoDB tables',
      'Control EC2 instances',
      'View CloudWatch logs',
      'Manage IAM roles',
      'Deploy CloudFormation stacks',
      'Access 200+ AWS services',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Kiro'],
    setupSteps: [
      'Configure AWS credentials (aws configure)',
      'Install: npx @aws/mcp-server',
      'Set AWS_REGION environment variable',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-23',
    slug: 'gmail-mcp',
    name: 'Gmail MCP',
    description: 'Read, send, and manage emails in Gmail — automate email workflows with AI.',
    longDescription: 'MCP server for Gmail integration. Read emails, compose and send messages, manage labels, search your inbox, and automate email workflows. Uses Google OAuth for secure access to your Gmail account.',
    githubUrl: 'https://github.com/nichochar/gmail-mcp',
    installCommand: 'npx gmail-mcp',
    owner: 'nichochar',
    category: 'Communication',
    categorySlug: 'communication',
    tags: ['Gmail', 'Email', 'Google', 'Inbox', 'Automation'],
    stars: 1100,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-02',
    features: [
      'Read and search emails',
      'Compose and send messages',
      'Manage labels and folders',
      'Handle attachments',
      'Draft management',
      'Thread conversations',
      'Filter and sort inbox',
      'Batch operations',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Create Google OAuth credentials at console.cloud.google.com',
      'Enable Gmail API',
      'Install: npx gmail-mcp',
      'Complete OAuth flow on first run',
    ],
  },
  {
    id: 'featured-24',
    slug: 'sqlite-mcp',
    name: 'SQLite MCP',
    description: 'Query and manage SQLite databases — perfect for local development and embedded data.',
    longDescription: 'MCP server for SQLite database interaction. Create databases, run queries, manage schemas, and analyze data in SQLite files. Ideal for local development, prototyping, and applications using embedded databases.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-sqlite',
    owner: 'modelcontextprotocol',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['SQLite', 'SQL', 'Database', 'Local', 'Embedded'],
    stars: 1400,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-05',
    features: [
      'Create and open databases',
      'Run SQL queries',
      'Manage table schemas',
      'Import/export data (CSV, JSON)',
      'View table statistics',
      'Index management',
      'Transaction support',
      'Database backup',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Install: npx @modelcontextprotocol/server-sqlite',
      'Point to your .db file path',
      'No API key needed — runs locally',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-25',
    slug: 'github-copilot-mcp',
    name: 'Sequential Thinking MCP',
    description: 'Give your AI structured reasoning — break complex problems into sequential thinking steps.',
    longDescription: 'MCP server that enables structured sequential thinking for AI assistants. Helps break down complex problems into manageable steps, maintain reasoning chains, and produce more accurate outputs for multi-step tasks.',
    githubUrl: 'https://github.com/modelcontextprotocol/servers',
    installCommand: 'npx @modelcontextprotocol/server-sequential-thinking',
    owner: 'modelcontextprotocol',
    category: 'AI & ML',
    categorySlug: 'ai-ml',
    tags: ['Reasoning', 'Thinking', 'Chain-of-Thought', 'AI', 'Logic'],
    stars: 1800,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-12',
    features: [
      'Structured reasoning chains',
      'Step-by-step problem decomposition',
      'Thought revision and branching',
      'Hypothesis tracking',
      'Multi-step verification',
      'Reasoning visualization',
      'Context window optimization',
      'Complex problem solving',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code', 'Windsurf'],
    setupSteps: [
      'Install: npx @modelcontextprotocol/server-sequential-thinking',
      'No API key needed',
      'Add to your AI client MCP config',
      'AI will use it automatically for complex tasks',
    ],
  },
  {
    id: 'featured-26',
    slug: 'spotify-mcp',
    name: 'Spotify MCP',
    description: 'Control Spotify playback, manage playlists, search music, and get recommendations with AI.',
    longDescription: 'MCP server for Spotify integration. Control playback, create and manage playlists, search for music, get personalized recommendations, and access your listening history through your AI assistant.',
    githubUrl: 'https://github.com/varunneal/spotify-mcp',
    installCommand: 'npx spotify-mcp',
    owner: 'varunneal',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Spotify', 'Music', 'Playlists', 'Playback', 'Streaming'],
    stars: 850,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-20',
    features: [
      'Control playback (play, pause, skip)',
      'Create and manage playlists',
      'Search tracks, albums, artists',
      'Get personalized recommendations',
      'View listening history',
      'Manage queue',
      'Access audio features',
      'Follow/unfollow artists',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Create a Spotify app at developer.spotify.com',
      'Get Client ID and Client Secret',
      'Install: npx spotify-mcp',
      'Complete OAuth flow on first run',
    ],
  },
  {
    id: 'featured-27',
    slug: 'raycast-mcp',
    name: 'Raycast MCP',
    description: 'Access Raycast extensions, clipboard history, snippets, and window management through AI.',
    longDescription: 'MCP server for Raycast productivity tool. Access your clipboard history, manage snippets, control window layouts, trigger extensions, and automate macOS workflows through your AI assistant.',
    githubUrl: 'https://github.com/raycast/raycast-mcp',
    installCommand: 'npx @raycast/mcp-server',
    owner: 'raycast',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Raycast', 'macOS', 'Productivity', 'Clipboard', 'Launcher'],
    stars: 780,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-15',
    features: [
      'Access clipboard history',
      'Manage text snippets',
      'Control window layouts',
      'Trigger Raycast extensions',
      'Quick calculations',
      'File search',
      'Calendar access',
      'System commands',
    ],
    compatibility: ['Claude Desktop', 'Cursor'],
    setupSteps: [
      'Install Raycast on macOS',
      'Install: npx @raycast/mcp-server',
      'Grant accessibility permissions',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-28',
    slug: 'twilio-mcp',
    name: 'Twilio MCP',
    description: 'Send SMS, make calls, manage phone numbers, and build communication workflows with Twilio.',
    longDescription: 'MCP server for Twilio communication platform. Send SMS messages, make voice calls, manage phone numbers, access call logs, and build automated communication workflows through your AI assistant.',
    githubUrl: 'https://github.com/twilio/twilio-mcp',
    installCommand: 'npx @twilio/mcp-server',
    owner: 'twilio',
    category: 'Communication',
    categorySlug: 'communication',
    tags: ['Twilio', 'SMS', 'Voice', 'Phone', 'Communication'],
    stars: 920,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-08',
    features: [
      'Send SMS messages',
      'Make voice calls',
      'Manage phone numbers',
      'Access call/message logs',
      'WhatsApp messaging',
      'Verify phone numbers',
      'Conference calls',
      'Programmable messaging',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get Twilio Account SID and Auth Token from console.twilio.com',
      'Install: npx @twilio/mcp-server',
      'Set TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN',
      'Restart your AI client',
    ],
  },
  {
    id: 'featured-29',
    slug: 'redis-mcp',
    name: 'Redis MCP',
    description: 'Interact with Redis — get/set keys, manage data structures, pub/sub, and cache operations.',
    longDescription: 'MCP server for Redis in-memory data store. Get and set keys, work with lists/sets/hashes, manage pub/sub channels, handle cache operations, and monitor Redis instances through your AI assistant.',
    githubUrl: 'https://github.com/redis/redis-mcp',
    installCommand: 'npx @redis/mcp-server',
    owner: 'redis',
    category: 'Data & Analytics',
    categorySlug: 'data-analytics',
    tags: ['Redis', 'Cache', 'Key-Value', 'Pub/Sub', 'In-Memory'],
    stars: 1050,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-04',
    features: [
      'Get/set key-value pairs',
      'Work with lists, sets, hashes',
      'Pub/sub messaging',
      'Key expiration management',
      'Pattern-based key search',
      'Monitor commands',
      'Memory usage analysis',
      'Cluster management',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Have a Redis instance running (local or cloud)',
      'Install: npx @redis/mcp-server',
      'Set REDIS_URL connection string',
      'Add to your AI client config',
    ],
  },
  {
    id: 'featured-30',
    slug: 'jira-mcp',
    name: 'Jira MCP',
    description: 'Manage Jira issues, sprints, and boards — streamline agile project management with AI.',
    longDescription: 'MCP server for Atlassian Jira. Create and update issues, manage sprints and boards, track epics, search with JQL, and automate agile workflows through your AI assistant. Supports both Jira Cloud and Server.',
    githubUrl: 'https://github.com/atlassian/jira-mcp',
    installCommand: 'npx @atlassian/jira-mcp-server',
    owner: 'atlassian',
    category: 'Productivity',
    categorySlug: 'productivity',
    tags: ['Jira', 'Agile', 'Sprints', 'Issues', 'Project Management'],
    stars: 1250,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-15',
    features: [
      'Create and update issues',
      'Manage sprints and boards',
      'Track epics and stories',
      'JQL search queries',
      'Transition issue status',
      'Manage components and versions',
      'Access sprint reports',
      'Bulk issue operations',
    ],
    compatibility: ['Claude Desktop', 'Cursor', 'VS Code'],
    setupSteps: [
      'Get a Jira API token from id.atlassian.com/manage-profile/security/api-tokens',
      'Install: npx @atlassian/jira-mcp-server',
      'Set JIRA_URL, JIRA_EMAIL, and JIRA_API_TOKEN',
      'Restart your AI client',
    ],
  },
]
