export interface IndiaMCP {
  id: string
  slug: string
  name: string
  description: string
  longDescription: string
  githubUrl: string
  npmPackage?: string
  installCommand: string
  owner: string
  ownerType: 'official' | 'community'
  category: string
  categorySlug: string
  tags: string[]
  stars: number
  language: string
  license: string
  lastUpdated: string
  verified: boolean
  features: string[]
  useCases: string[]
}

export const INDIA_MCPS: IndiaMCP[] = [
  // === OFFICIAL (Made by the companies themselves) ===
  {
    id: 'india-1',
    slug: 'zerodha-kite-mcp',
    name: 'Zerodha Kite MCP',
    description: 'Official Zerodha MCP server for stock trading, portfolio management, and real-time market data via Kite Connect APIs.',
    longDescription: 'The official MCP server from Zerodha — India\'s largest discount broker. Connect your AI assistant directly to Kite Connect APIs for live trading, portfolio tracking, order management, and real-time NSE/BSE market data. Built and maintained by the Zerodha engineering team.',
    githubUrl: 'https://github.com/zerodha/kite-mcp-server',
    installCommand: 'npx @zerodha/kite-mcp-server',
    owner: 'zerodha',
    ownerType: 'official',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Trading', 'Stocks', 'NSE', 'BSE', 'Portfolio', 'Kite Connect'],
    stars: 245,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-28',
    verified: true,
    features: [
      'Place buy/sell orders (market, limit, SL)',
      'Track portfolio holdings & positions',
      'Get real-time quotes & market depth',
      'View order history & trade book',
      'Manage GTT (Good Till Triggered) orders',
      'Access historical candle data',
    ],
    useCases: [
      'AI-powered trading bot',
      'Portfolio analysis assistant',
      'Market research automation',
      'Automated alerts & notifications',
    ],
  },
  {
    id: 'india-2',
    slug: 'razorpay-mcp',
    name: 'Razorpay MCP',
    description: 'Official Razorpay MCP server for payment processing, refunds, subscriptions, and UPI payment links.',
    longDescription: 'The official MCP server from Razorpay — India\'s leading payment gateway. Process payments, manage refunds, create payment links, handle subscriptions, and access transaction data. Supports UPI, cards, netbanking, and wallets. Built by the Razorpay team.',
    githubUrl: 'https://github.com/razorpay/razorpay-mcp-server',
    installCommand: 'npx @razorpay/mcp-server',
    owner: 'razorpay',
    ownerType: 'official',
    category: 'Payments',
    categorySlug: 'payments',
    tags: ['Payments', 'UPI', 'Cards', 'Subscriptions', 'Refunds', 'Payment Links'],
    stars: 189,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-25',
    verified: true,
    features: [
      'Create & capture payments',
      'Process refunds (full & partial)',
      'Generate payment links',
      'Manage subscriptions & plans',
      'Fetch transaction history',
      'Handle UPI collect requests',
    ],
    useCases: [
      'Automated payment collection',
      'Refund processing bot',
      'Subscription management',
      'Financial reconciliation',
    ],
  },
  {
    id: 'india-3',
    slug: 'zomato-mcp',
    name: 'Zomato MCP',
    description: 'Official Zomato MCP server for food ordering, restaurant discovery, and delivery tracking.',
    longDescription: 'The official MCP server from Zomato — India\'s largest food delivery platform. Search restaurants, browse menus, place orders, and track deliveries through your AI assistant. Built by the Zomato engineering team.',
    githubUrl: 'https://github.com/Zomato/mcp-server-manifest',
    installCommand: 'npx @zomato/mcp-server',
    owner: 'Zomato',
    ownerType: 'official',
    category: 'Food & Delivery',
    categorySlug: 'e-commerce',
    tags: ['Food', 'Delivery', 'Restaurants', 'Orders', 'India'],
    stars: 156,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-10',
    verified: true,
    features: [
      'Search restaurants by location & cuisine',
      'Browse menus & prices',
      'Place food orders',
      'Track delivery status',
      'View order history',
      'Apply coupons & offers',
    ],
    useCases: [
      'AI food ordering assistant',
      'Restaurant recommendation bot',
      'Meal planning automation',
      'Expense tracking for food',
    ],
  },
  {
    id: 'india-4',
    slug: 'browserstack-mcp',
    name: 'BrowserStack MCP',
    description: 'Official BrowserStack MCP server for cross-browser testing, device farms, and automated test execution.',
    longDescription: 'The official MCP server from BrowserStack — India\'s leading testing platform (unicorn). Run automated tests across 3000+ real browsers and devices, manage test sessions, and access test results through your AI assistant.',
    githubUrl: 'https://github.com/browserstack/mcp-server',
    installCommand: 'npx @browserstack/mcp-server',
    owner: 'browserstack',
    ownerType: 'official',
    category: 'Developer Tools',
    categorySlug: 'developer-tools',
    tags: ['Testing', 'Browsers', 'Automation', 'QA', 'DevOps'],
    stars: 312,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-03-15',
    verified: true,
    features: [
      'Run tests on 3000+ browser/device combos',
      'Capture screenshots & videos',
      'Access test logs & reports',
      'Manage test sessions',
      'Integrate with CI/CD pipelines',
      'Debug failed tests with AI',
    ],
    useCases: [
      'Automated cross-browser testing',
      'Visual regression detection',
      'Test failure analysis',
      'QA workflow automation',
    ],
  },

  // === COMMUNITY (Made by Indian developers) ===
  {
    id: 'india-5',
    slug: 'nse-bse-mcp',
    name: 'NSE/BSE Market Data MCP',
    description: 'Real-time and historical stock market data from NSE and BSE exchanges via Streamable HTTP transport.',
    longDescription: 'Community-built MCP server providing live market data from both National Stock Exchange (NSE) and Bombay Stock Exchange (BSE). Get real-time stock prices, index values, historical data, and market statistics. Uses free public APIs — no paid subscription needed.',
    githubUrl: 'https://github.com/bshada/nse-bse-mcp',
    installCommand: 'npx nse-bse-mcp',
    owner: 'bshada',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['NSE', 'BSE', 'Stocks', 'Market Data', 'Free API', 'Real-time'],
    stars: 87,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-20',
    verified: false,
    features: [
      'Live stock prices (NSE + BSE)',
      'Index values (Nifty 50, Sensex, etc.)',
      'Historical OHLCV data',
      'Market breadth & advances/declines',
      'Sector-wise performance',
      'No API key required (free)',
    ],
    useCases: [
      'Market research & analysis',
      'Stock screening',
      'Portfolio monitoring',
      'Technical analysis data feed',
    ],
  },
  {
    id: 'india-6',
    slug: 'indian-stock-agent',
    name: 'Indian Stock & MF Agent',
    description: 'MCP agent for Indian stocks, mutual funds, and crypto with portfolio analysis and recommendations.',
    longDescription: 'A comprehensive MCP agent built for Indian investors. Covers stocks (NSE/BSE), mutual funds (AMFI), and cryptocurrency. Provides portfolio analysis, stock screening, MF comparisons, and investment recommendations tailored to the Indian market.',
    githubUrl: 'https://github.com/Sparker0i/indian-stock-mcp-agent',
    installCommand: 'npx indian-stock-mcp-agent',
    owner: 'Sparker0i',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Stocks', 'Mutual Funds', 'Crypto', 'India', 'Portfolio', 'AMFI'],
    stars: 64,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-03-10',
    verified: false,
    features: [
      'Indian stock data (NSE/BSE)',
      'Mutual fund NAV & returns',
      'Crypto prices (INR pairs)',
      'Portfolio analysis & tracking',
      'Stock screening & filtering',
      'SIP calculator & projections',
    ],
    useCases: [
      'Investment research assistant',
      'MF comparison & selection',
      'Portfolio rebalancing',
      'Tax-loss harvesting analysis',
    ],
  },
  {
    id: 'india-7',
    slug: 'indian-railways-mcp',
    name: 'Indian Railways MCP',
    description: 'Live train status, station info, and PNR tracking from Indian Railways using Model Context Protocol.',
    longDescription: 'MCP server for Indian Railways data. Get live train running status, station arrivals/departures, PNR status, seat availability, and train schedules. Built for the 8 billion+ annual railway passengers in India.',
    githubUrl: 'https://github.com/rajprem4214/indian-railways-mcp',
    installCommand: 'npx indian-railways-mcp',
    owner: 'rajprem4214',
    ownerType: 'community',
    category: 'Travel & Transport',
    categorySlug: 'government',
    tags: ['Railways', 'Trains', 'PNR', 'IRCTC', 'Travel', 'India'],
    stars: 42,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-13',
    verified: false,
    features: [
      'Live train running status',
      'Station arrivals & departures',
      'PNR status checking',
      'Train schedule & route',
      'Seat availability check',
      'Station code lookup',
    ],
    useCases: [
      'Travel planning assistant',
      'PNR tracking bot',
      'Train delay notifications',
      'Journey planning optimization',
    ],
  },
  {
    id: 'india-8',
    slug: 'zerodha-community-mcp',
    name: 'Zerodha Kite (Community)',
    description: 'Community-built MCP server for Zerodha Kite trade APIs with extended features and Python support.',
    longDescription: 'An alternative community-built MCP server for Zerodha\'s Kite Connect APIs. Offers Python-based implementation with additional features like backtesting support, custom indicators, and batch order placement. Good for developers who prefer Python over the official TypeScript version.',
    githubUrl: 'https://github.com/aptro/zerodha-mcp',
    installCommand: 'pip install zerodha-mcp',
    owner: 'aptro',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Zerodha', 'Trading', 'Python', 'Kite', 'Backtesting'],
    stars: 38,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-02-20',
    verified: false,
    features: [
      'All Kite Connect API endpoints',
      'Python-native implementation',
      'Backtesting support',
      'Custom technical indicators',
      'Batch order placement',
      'WebSocket streaming data',
    ],
    useCases: [
      'Algorithmic trading in Python',
      'Strategy backtesting',
      'Custom indicator development',
      'Automated trading systems',
    ],
  },
  {
    id: 'india-9',
    slug: 'indic-translate-skill',
    name: 'Indic Translation Skill',
    description: 'AI4Bharat IndicTrans2 — translate between 22 Indian languages with state-of-the-art accuracy.',
    longDescription: 'Based on AI4Bharat\'s IndicTrans2 model — the most accurate translation system for Indian languages. Supports all 22 scheduled languages of India including Hindi, Tamil, Telugu, Bengali, Marathi, Gujarati, Kannada, Malayalam, and more. Can be used as an MCP skill for multilingual AI assistants.',
    githubUrl: 'https://github.com/AI4Bharat/IndicTrans2',
    installCommand: 'pip install indictrans2',
    owner: 'AI4Bharat',
    ownerType: 'community',
    category: 'AI & Language',
    categorySlug: 'ai-ml',
    tags: ['Translation', 'Hindi', 'Tamil', 'Telugu', 'NLP', '22 Languages'],
    stars: 1200,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-01-15',
    verified: false,
    features: [
      'Translate between 22 Indian languages',
      'English ↔ Indian language pairs',
      'Indian language ↔ Indian language',
      'Batch translation support',
      'High accuracy (SOTA on Flores)',
      'Runs locally (no API needed)',
    ],
    useCases: [
      'Multilingual chatbot',
      'Document translation',
      'Content localization',
      'Cross-language search',
    ],
  },
  {
    id: 'india-10',
    slug: 'indic-tts-skill',
    name: 'Indic Text-to-Speech Skill',
    description: 'AI4Bharat Indic-TTS — natural text-to-speech for Indian languages including Hindi, Tamil, Telugu, and more.',
    longDescription: 'Text-to-Speech system for Indian languages by AI4Bharat. Generate natural-sounding speech in Hindi, Tamil, Telugu, Bengali, Marathi, and other Indian languages. Useful as an MCP skill for voice-enabled AI assistants serving Indian users.',
    githubUrl: 'https://github.com/AI4Bharat/Indic-TTS',
    installCommand: 'pip install indic-tts',
    owner: 'AI4Bharat',
    ownerType: 'community',
    category: 'AI & Language',
    categorySlug: 'ai-ml',
    tags: ['TTS', 'Voice', 'Hindi', 'Indian Languages', 'Speech', 'AI'],
    stars: 890,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-02-01',
    verified: false,
    features: [
      'Natural speech in 13+ Indian languages',
      'Multiple voice options per language',
      'Adjustable speed & pitch',
      'SSML support',
      'Runs locally (no cloud needed)',
      'Low latency inference',
    ],
    useCases: [
      'Voice assistant in Indian languages',
      'Audio content generation',
      'Accessibility tools',
      'IVR systems',
    ],
  },
  {
    id: 'india-11',
    slug: 'whatsapp-mcp',
    name: 'WhatsApp MCP',
    description: 'Send and receive WhatsApp messages through AI — essential for India where 500M+ people use WhatsApp daily.',
    longDescription: 'MCP server for WhatsApp messaging. Send messages, read conversations, manage contacts, and automate WhatsApp workflows. Critical for India where WhatsApp is the primary communication tool for businesses and individuals alike.',
    githubUrl: 'https://github.com/lharries/whatsapp-mcp',
    installCommand: 'npx whatsapp-mcp',
    owner: 'lharries',
    ownerType: 'community',
    category: 'Communication',
    categorySlug: 'communication',
    tags: ['WhatsApp', 'Messaging', 'Chat', 'Business', 'India'],
    stars: 520,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-01',
    verified: false,
    features: [
      'Send & receive messages',
      'Read conversation history',
      'Send media (images, docs)',
      'Group messaging',
      'Contact management',
      'Message search',
    ],
    useCases: [
      'Customer support automation',
      'Business communication bot',
      'Order notifications',
      'Appointment reminders',
    ],
  },
  {
    id: 'india-12',
    slug: 'sarvam-ai-skill',
    name: 'Sarvam AI Voice Skill',
    description: 'Sarvam AI — Indian voice AI platform for speech recognition and synthesis in Indian languages.',
    longDescription: 'Sarvam AI is building India\'s voice AI infrastructure. Their models support speech recognition (ASR) and text-to-speech (TTS) for major Indian languages. Can be integrated as an MCP skill for voice-enabled AI applications targeting Indian users.',
    githubUrl: 'https://github.com/sarvamai',
    installCommand: 'pip install sarvam-ai',
    owner: 'sarvamai',
    ownerType: 'community',
    category: 'AI & Language',
    categorySlug: 'ai-ml',
    tags: ['Voice AI', 'ASR', 'TTS', 'Indian Languages', 'Speech Recognition'],
    stars: 340,
    language: 'Python',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-01',
    verified: false,
    features: [
      'Speech recognition (Hindi, Tamil, etc.)',
      'Text-to-speech (natural voices)',
      'Language detection',
      'Code-switching support (Hinglish)',
      'Real-time streaming ASR',
      'Custom vocabulary support',
    ],
    useCases: [
      'Voice-enabled AI assistant',
      'Call center automation',
      'Voice search in Indian languages',
      'Podcast transcription',
    ],
  },
  // === NEW INDIA MCPs ===
  {
    id: 'india-13',
    slug: 'upstox-mcp',
    name: 'Upstox Trading MCP',
    description: 'MCP server for Upstox trading platform — place orders, track portfolio, and get real-time market data.',
    longDescription: 'Community-built MCP server for Upstox, one of India\'s fastest-growing discount brokers. Access the Upstox API to place equity/F&O orders, track your portfolio, get live quotes, and manage watchlists through your AI assistant.',
    githubUrl: 'https://github.com/PradeepJaiswar/mcp-server-upstox-api',
    installCommand: 'npx mcp-server-upstox-api',
    owner: 'PradeepJaiswar',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Upstox', 'Trading', 'Stocks', 'F&O', 'India'],
    stars: 28,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-15',
    verified: false,
    features: [
      'Place equity & F&O orders',
      'Track portfolio holdings',
      'Get real-time quotes',
      'Manage watchlists',
      'View order & trade history',
      'Access historical data',
    ],
    useCases: [
      'Automated trading via Upstox',
      'Portfolio monitoring',
      'Options strategy execution',
      'Market data analysis',
    ],
  },
  {
    id: 'india-14',
    slug: 'groww-mcp',
    name: 'Groww Investment MCP',
    description: 'MCP server for Groww — trade stocks, track mutual funds, and manage your investment portfolio.',
    longDescription: 'Community-built MCP server for Groww, India\'s popular investment platform with 10 crore+ users. Access stock trading, mutual fund investments, portfolio tracking, and market data through your AI assistant.',
    githubUrl: 'https://github.com/karthik1729/groww-mcp',
    installCommand: 'npx groww-mcp',
    owner: 'karthik1729',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Groww', 'Stocks', 'Mutual Funds', 'India', 'Investment'],
    stars: 22,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-20',
    verified: false,
    features: [
      'Stock trading (buy/sell)',
      'Mutual fund SIP management',
      'Portfolio tracking & P&L',
      'Market data & quotes',
      'IPO applications',
      'Watchlist management',
    ],
    useCases: [
      'Investment portfolio assistant',
      'SIP automation',
      'Stock research & screening',
      'IPO tracking',
    ],
  },
  {
    id: 'india-15',
    slug: 'groww-mcp-server',
    name: 'Groww MCP Server (Alt)',
    description: 'Alternative Groww MCP server with focus on mutual fund analysis and portfolio optimization.',
    longDescription: 'Another community implementation for Groww focused on mutual fund analytics. Compare funds, analyze returns, track NAVs, and get AI-powered investment recommendations for the Indian market.',
    githubUrl: 'https://github.com/arkapravasinha/groww-mcp-server',
    installCommand: 'npx groww-mcp-server',
    owner: 'arkapravasinha',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['Groww', 'Mutual Funds', 'NAV', 'SIP', 'India'],
    stars: 15,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-03-28',
    verified: false,
    features: [
      'Mutual fund NAV tracking',
      'Fund comparison & analysis',
      'SIP return calculator',
      'Portfolio optimization',
      'Category-wise fund screening',
      'Historical performance data',
    ],
    useCases: [
      'MF research assistant',
      'SIP planning',
      'Fund comparison',
      'Portfolio rebalancing',
    ],
  },
  // === NEWLY DISCOVERED ===
  {
    id: 'india-16',
    slug: 'swiggy-mcp',
    name: 'Swiggy MCP',
    description: 'Official Swiggy MCP server for food ordering, restaurant search, and delivery tracking.',
    longDescription: 'The official MCP server from Swiggy — India\'s leading food and grocery delivery platform. Order food, search restaurants, track deliveries, and manage your Swiggy account through your AI assistant. Built by the Swiggy engineering team.',
    githubUrl: 'https://github.com/Swiggy/swiggy-mcp-server-manifest',
    installCommand: 'npx @swiggy/mcp-server',
    owner: 'Swiggy',
    ownerType: 'official',
    category: 'Food & Delivery',
    categorySlug: 'e-commerce',
    tags: ['Swiggy', 'Food', 'Delivery', 'Restaurants', 'Grocery'],
    stars: 120,
    language: 'TypeScript',
    license: 'Apache-2.0',
    lastUpdated: '2025-05-20',
    verified: true,
    features: [
      'Search restaurants by location',
      'Browse menus and prices',
      'Place food orders',
      'Track delivery in real-time',
      'Grocery ordering (Instamart)',
      'View order history & reorder',
    ],
    useCases: [
      'AI food ordering assistant',
      'Restaurant discovery',
      'Grocery automation',
      'Meal planning with delivery',
    ],
  },
  {
    id: 'india-17',
    slug: 'mcp-india-stack',
    name: 'MCP India Stack',
    description: '30 tools for PAN, Aadhaar, GSTIN validation, Income Tax, TDS, GST calculation, and master data lookups.',
    longDescription: 'Comprehensive MCP server for India Stack — the digital infrastructure layer. Includes 30 dedicated tools for identity validation (PAN, Aadhaar, GSTIN), tax calculation (Income Tax, TDS, GST), and master data lookups. Enterprise-ready with thread-pool accelerated bulk validation.',
    githubUrl: 'https://github.com/rehan1020/mcp-india-stack',
    installCommand: 'npx mcp-india-stack',
    owner: 'rehan1020',
    ownerType: 'community',
    category: 'Government & Compliance',
    categorySlug: 'government',
    tags: ['PAN', 'Aadhaar', 'GSTIN', 'Tax', 'India Stack', 'KYC'],
    stars: 95,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-05-25',
    verified: false,
    features: [
      'PAN card validation & lookup',
      'Aadhaar number verification',
      'GSTIN validation & details',
      'Income Tax calculation',
      'TDS rate lookup',
      'GST rate finder',
      'Bulk validation (enterprise)',
      'Auto-updating datasets via CDN',
    ],
    useCases: [
      'KYC automation',
      'Tax compliance assistant',
      'Vendor verification',
      'Invoice validation',
    ],
  },
  {
    id: 'india-18',
    slug: 'india-flight-mcp',
    name: 'India Flight Search MCP',
    description: 'Find the cheapest airfares for domestic and international flights from India.',
    longDescription: 'MCP server to search and compare flight prices for Indian travelers. Find the cheapest fares across airlines, compare routes, and get price alerts. Covers domestic flights (IndiGo, SpiceJet, Air India, Vistara) and international routes from Indian airports.',
    githubUrl: 'https://github.com/ravi-bytes/india-flight-mcp',
    installCommand: 'npx india-flight-mcp',
    owner: 'ravi-bytes',
    ownerType: 'community',
    category: 'Travel & Transport',
    categorySlug: 'government',
    tags: ['Flights', 'Travel', 'Airfare', 'India', 'Airlines'],
    stars: 35,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-10',
    verified: false,
    features: [
      'Search domestic flights',
      'Compare prices across airlines',
      'Find cheapest fare dates',
      'International flight search',
      'Multi-city route planning',
      'Price alert notifications',
    ],
    useCases: [
      'Travel planning assistant',
      'Cheapest fare finder',
      'Trip budget optimization',
      'Corporate travel booking',
    ],
  },
  {
    id: 'india-19',
    slug: 'icici-direct-mcp',
    name: 'ICICI Direct MCP',
    description: 'MCP server for ICICI Direct trading platform — stocks, mutual funds, and derivatives.',
    longDescription: 'Community-built MCP server for ICICI Direct, one of India\'s largest full-service brokers. Trade stocks, invest in mutual funds, access research reports, and manage your demat account through your AI assistant.',
    githubUrl: 'https://github.com/nicodishanthj/icici-direct-mcp-server',
    installCommand: 'npx icici-direct-mcp-server',
    owner: 'nicodishanthj',
    ownerType: 'community',
    category: 'Finance & Trading',
    categorySlug: 'finance',
    tags: ['ICICI', 'Trading', 'Stocks', 'Mutual Funds', 'Demat'],
    stars: 18,
    language: 'TypeScript',
    license: 'MIT',
    lastUpdated: '2025-04-05',
    verified: false,
    features: [
      'Stock trading (equity & F&O)',
      'Mutual fund investments',
      'Research reports access',
      'Portfolio tracking',
      'Demat account management',
      'IPO applications',
    ],
    useCases: [
      'Trading via ICICI Direct',
      'MF investment automation',
      'Portfolio analysis',
      'Research-based trading',
    ],
  },
  {
    id: 'india-20',
    slug: 'naukri-automation',
    name: 'Naukri.com Auto-Apply Bot',
    description: 'Automate job applications on Naukri.com — auto-apply, profile updates, and job search.',
    longDescription: 'Automation tool for Naukri.com, India\'s largest job portal. Auto-apply to matching jobs, keep your profile updated (recently updated profiles get more recruiter views), and automate the job search process. Uses Selenium for browser automation.',
    githubUrl: 'https://github.com/GoliathReaper/JobSailor',
    installCommand: 'git clone https://github.com/GoliathReaper/JobSailor',
    owner: 'GoliathReaper',
    ownerType: 'community',
    category: 'Jobs & Career',
    categorySlug: 'automation',
    tags: ['Naukri', 'Jobs', 'Auto-Apply', 'Career', 'Recruitment'],
    stars: 180,
    language: 'Python',
    license: 'MIT',
    lastUpdated: '2025-03-20',
    verified: false,
    features: [
      'Auto-apply to matching jobs',
      'Profile auto-update (daily)',
      'Job search with filters',
      'Answer application questions',
      'Resume upload automation',
      'Application tracking',
    ],
    useCases: [
      'Automated job hunting',
      'Profile visibility boost',
      'Bulk job applications',
      'Career transition support',
    ],
  },
]

// Helper to get official vs community
export const OFFICIAL_INDIA_MCPS = INDIA_MCPS.filter(m => m.ownerType === 'official')
export const COMMUNITY_INDIA_MCPS = INDIA_MCPS.filter(m => m.ownerType === 'community')
