/**
 * Seed Data Generator for BharatMCP
 * 
 * Takes data/mcps.json (output from scrape-mcps.ts) and generates
 * a Prisma-compatible seed file for database population.
 * 
 * Run with: npx tsx scripts/generate-seed-data.ts
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join } from 'path'

interface ScrapedMCP {
  name: string
  slug: string
  description: string
  githubUrl: string
  type: 'mcp' | 'skill' | 'agent' | 'workflow'
  category: string
  categorySlug: string
  country: 'india' | 'global'
  verificationTier: 'bharatmcp_verified' | 'community_verified' | 'listed'
  tags: string[]
  owner: string
}

function randomInRange(min: number, max: number, seed: number): number {
  const x = Math.sin(seed * 9301 + 49297) * 49297
  const r = x - Math.floor(x)
  return Math.floor(min + r * (max - min))
}

function randomFloat(min: number, max: number, seed: number): number {
  const x = Math.sin(seed * 9301 + 49297) * 49297
  const r = x - Math.floor(x)
  return Math.round((min + r * (max - min)) * 10) / 10
}

function randomDate(startYear: number, endYear: number, seed: number): string {
  const x = Math.sin(seed * 9301 + 49297) * 49297
  const r = x - Math.floor(x)
  const start = new Date(startYear, 0, 1).getTime()
  const end = new Date(endYear, 11, 31).getTime()
  const date = new Date(start + r * (end - start))
  return date.toISOString()
}

async function main() {
  const dataPath = join(process.cwd(), 'data', 'mcps.json')

  if (!existsSync(dataPath)) {
    console.error('❌ data/mcps.json not found. Run `npx tsx scripts/scrape-mcps.ts` first.')
    process.exit(1)
  }

  const mcps: ScrapedMCP[] = JSON.parse(readFileSync(dataPath, 'utf-8'))
  console.log(`📦 Loaded ${mcps.length} entries from data/mcps.json`)

  // Generate Prisma seed data
  const seedEntries = mcps.slice(0, 250).map((mcp, index) => {
    const seed = index + 1
    return {
      slug: mcp.slug,
      name: mcp.name,
      description: mcp.description,
      type: mcp.type.toUpperCase(),
      categorySlug: mcp.categorySlug,
      tags: mcp.tags,
      verificationTier: mcp.verificationTier.toUpperCase(),
      country: mcp.country,
      rating: randomFloat(3.5, 5.0, seed),
      reviewCount: randomInRange(5, 120, seed * 2),
      downloadCount: randomInRange(500, 50000, seed * 3),
      installCount: randomInRange(200, 30000, seed * 4),
      starCount: randomInRange(10, 2000, seed * 5),
      version: `${randomInRange(1, 3, seed * 6)}.${randomInRange(0, 9, seed * 7)}.${randomInRange(0, 9, seed * 8)}`,
      license: ['MIT', 'Apache-2.0', 'ISC', 'BSD-3-Clause', 'GPL-3.0'][randomInRange(0, 4, seed * 9)],
      repoUrl: mcp.githubUrl,
      creatorUsername: mcp.owner,
      createdAt: randomDate(2024, 2024, seed * 10),
      updatedAt: randomDate(2025, 2025, seed * 11),
    }
  })

  const seedContent = `// Auto-generated seed data from scraped MCP sources
// Generated by: npx tsx scripts/generate-seed-data.ts
// Run after: npx tsx scripts/scrape-mcps.ts

export const SEED_PROJECTS = ${JSON.stringify(seedEntries, null, 2)}

export const SEED_CATEGORIES = [
  { slug: 'developer-tools', name: 'Developer Tools', description: 'Code editors, version control, CI/CD, and development workflow integrations.', icon: 'code' },
  { slug: 'finance', name: 'Finance', description: 'Payment gateways, trading platforms, banking APIs, and financial data services.', icon: 'chart' },
  { slug: 'payments', name: 'Payments', description: 'Payment processing, billing, invoicing, and subscription management.', icon: 'credit-card' },
  { slug: 'communication', name: 'Communication', description: 'Messaging platforms, email services, and team collaboration tools.', icon: 'message' },
  { slug: 'productivity', name: 'Productivity', description: 'Note-taking, project management, calendars, and workflow automation.', icon: 'layers' },
  { slug: 'ai-ml', name: 'AI & ML', description: 'Machine learning models, AI APIs, data processing, and model deployment tools.', icon: 'brain' },
  { slug: 'data-analytics', name: 'Data & Analytics', description: 'Databases, data warehouses, visualization tools, and analytics platforms.', icon: 'database' },
  { slug: 'cloud-infra', name: 'Cloud & Infrastructure', description: 'Cloud providers, container orchestration, serverless, and DevOps tools.', icon: 'cloud' },
  { slug: 'security', name: 'Security', description: 'Authentication, authorization, vulnerability scanning, and compliance tools.', icon: 'shield' },
  { slug: 'automation', name: 'Automation', description: 'Workflow automation, scheduling, event-driven pipelines, and integrations.', icon: 'zap' },
  { slug: 'e-commerce', name: 'E-commerce', description: 'Online stores, marketplaces, inventory management, and order processing.', icon: 'shopping-cart' },
  { slug: 'government', name: 'Government', description: 'UPI, Aadhaar, GST, IRCTC, and other India-specific government and private APIs.', icon: 'flag' },
]
`

  const outputPath = join(process.cwd(), 'data', 'seed-data.ts')
  writeFileSync(outputPath, seedContent)
  console.log(`💾 Generated seed data at ${outputPath}`)
  console.log(`   ${seedEntries.length} projects ready for database seeding`)
}

main()
